site_name: abx-next
repo_url: https://github.com/DiogoRibeiro7/abx-next
theme: { name: material }
nav:
  - Home: index.md
  - Concepts:
    - Variance reduction: concepts/variance_reduction.md
    - Sequential: concepts/sequential.md
    - Switchback: concepts/switchback.md
